"""initital migration

Revision ID: dba7fd06eeb0
Revises: 
Create Date: 2023-05-10 13:26:30.523293

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dba7fd06eeb0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('long_desc',
               existing_type=mysql.VARCHAR(length=150),
               type_=sa.String(length=1000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('long_desc',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=150),
               existing_nullable=True)

    # ### end Alembic commands ###
