from ..models import Product

tractor_items = [
        Product(
            name="Rust Bucket",
            price=500,
            emissions=20,
            image="tractor1.jpg",
            short_desc="This tractor will leave you feeling rusty.",
            long_desc="The Rust Bucket is a classic example of a tractor that's seen better days. It's covered in rust and has more holes than a block of Swiss cheese. It may not be pretty, but it'll get the job done.",
            ),
        Product(
            name="Smokestack",
            price=1000,
            emissions=30,
            image="tractor2.jpg",
            short_desc="This tractor will keep you warm all winter long.",
            long_desc="The Smokestack is a tractor that loves to smoke. It belches out black smoke like a coal-fired power plant. But at least it'll keep you warm in the winter.",
            ),
        Product(
            name="Flatulent",
            price=800,
            emissions=25,
            image="tractor3.png",
            short_desc="This tractor will clear your sinuses.",
            long_desc="The Flatulent is a tractor that's known for its gas. It's not uncommon to hear it farting around the fields. But hey, at least it'll clear your sinuses.",
            ),
        Product(
            name="Sputterbug",
            price=1200,
            emissions=35,
            image="tractor5.jpg",
            short_desc="This tractor has a mind of its own.",
            long_desc="The Sputterbug is a tractor that likes to sputter. It'll run fine for a while, and then suddenly start acting up. It's like it has a mind of its own.",
            ),
        Product(
            name="Clunker",
            price=600,
            emissions=22,
            image="tractor4.jpg",
            short_desc="This tractor is a real clunker.",
            long_desc="The Clunker is a tractor that's seen better days. It's covered in dents and scratches and makes all sorts of strange noises. But it'll still get the job done.",
            ),
        Product(
            name="Rattletrap",
            price=700,
            emissions=23,
            image="tractor6.jpg",
            short_desc="This tractor is a real rattletrap.",
            long_desc="The Rattletrap is a tractor that's so loud, you'll need earplugs just to drive it. But hey, at least it runs.",
            ),
        Product(
            name="Lawn Dart",
            price=1500,
            emissions=40,
            image="tractor7.jpg",
            short_desc="This tractor is like a lawn dart.",
            long_desc="The Lawn Dart is a tractor that's so fast, it's like a missile on wheels. But be careful - it's hard to control.",
            ),
        Product(
                name="Junker",
                price=400,
                emissions=18,
                image="tractor8.jpg",
                short_desc="This tractor is a real junker.",
                long_desc="The Junker is a tractor that's been around the block a few times. It's covered in rust and barely runs, but it'll still get the job done.",
                ),
        Product(
                name="Rustmobile",
                price=550,
                emissions=21,
                image="tractor9.jpg",
                short_desc="This tractor is like a mobile rust bucket.",
                long_desc="The Rustmobile is a tractor that's covered in rust from top to bottom. It looks like it's about to fall apart, but somehow it keeps going.",
                ),
        Product(
                name="LEGO Tractor",
                price=650,
                emissions=24,
                image="tractor10.jpg",
                short_desc="Exclusive LEGO partnership. 8.5 ton pulling power.",
                long_desc="A miniature tractor that looks and functions like a real one, but built on a smaller scale. Its sturdy frame, engine, wheels and other features make it a great collectible and display piece. Perfect for anyone who loves tractors!",
                ),
        Product(
                name="Haywire",
                price=900,
                emissions=28,
                image="tractor11.jpg",
                short_desc="This tractor is a little haywire.",
                long_desc="The Haywire is a tractor that's a bit unpredictable. It might run perfectly fine one day, and then refuse to start the next. But when it's running, it gets the job done.",
                ),
        Product(
                name="Screaming Eagle",
                price=2000,
                emissions=50,
                image="tractor12.jpg",
                short_desc="This tractor is like a screaming eagle.",
                long_desc="The Screaming Eagle is a tractor that's so fast, it'll make your head spin. It's like a bird of prey, swooping down on its prey. But be careful - it's hard to control.",
                ),
        Product(
                name="Rustbucket Deluxe",
                price=750,
                emissions=23,
                image="tractor13.jpg",
                short_desc="This tractor is a deluxe rust bucket.",
                long_desc="The Rustbucket Deluxe is a tractor that's seen better days, but it's still got some fancy features. It's got a deluxe seat and a fancy paint job - too bad it's covered in rust.",
                ),
        Product(
                name="Chitty Chitty Bang Bang",
                price=3000,
                emissions=70,
                image="tractor14.jpg",
                short_desc="This tractor is like Chitty Chitty Bang Bang.",
                long_desc="The Chitty Chitty Bang Bang is a tractor that's a bit of a mystery. It looks like it's straight out of a children's book, with its bright colors and quirky design. But it's got some serious power under the hood.",
                ),
        Product(
                name="Rattle and Roll",
                price=850,
                emissions=26,
                image="tractor15.jpg",
                short_desc="This tractor likes to rattle and roll.",
                long_desc="The Rattle and Roll is a tractor that's so loud, you can hear it coming from miles away. It's like a rock star on wheels, shaking and rattling all the way.",
                ),
    ]
